# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:46
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'curso_turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('carga_horaria', models.SmallIntegerField()),
                ('aula_teorica', models.DecimalField(decimal_places=3, max_digits=10)),
                ('aula_pratica', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('competencias', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('bibliografia_basica', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'disciplina_ofertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_turma', models.CharField(max_length=2)),
                ('turno', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(default='C', max_length=1, verbose_name='Tipo de usuário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('semestre', models.IntegerField(default=1, verbose_name='Semestre')),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('turma', models.ManyToManyField(through='core.Matricula', to='core.Turma')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='Apelido')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
    ]
