# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171126_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('sala', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.AlterModelTable(
            name='curso',
            table='CURSO',
        ),
        migrations.AlterModelTable(
            name='turma',
            table='TURMA',
        ),
    ]
