CREATE DATABASE FACULDADE;
go

USE FACULDADE;
go

CREATE TABLE Disciplina(
	ID INT IDENTITY(1,1),
	NOME VARCHAR(240) NOT NULL,
	CARGA_HORARIA TINYINT NOT NULL,
	TEORIA DECIMAL(3),
	PRATICA DECIMAL(3),
	EMENTA TEXT,
	COMPETENCIAS TEXT,
	HABILIDADES TEXT,
	CONTEUDO TEXT,
	BIB_BASICA TEXT,
	BIB_COMPLEMENTAR TEXT,
	CONSTRAINT pkDisciplina PRIMARY KEY (ID),
	CONSTRAINT uqDisciplinaNome UNIQUE (NOME)
);

CREATE TABLE Curso(
	ID INT IDENTITY(1,1),
	SIGLA VARCHAR(5) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CONSTRAINT pkCurso PRIMARY KEY (ID),
	CONSTRAINT uqCursoSigla UNIQUE (SIGLA),
	CONSTRAINT uqCursoNome UNIQUE (NOME)
);

CREATE TABLE Aluno(
	ID INT IDENTITY(1,1),
	RA_ALUNO INT NOT NULL,
	NOME VARCHAR(120) NOT NULL,
	EMAIL VARCHAR(80) NOT NULL,
	CELULAR CHAR(11) NOT NULL,
	ID_CURSO INT NOT NULL,
	CONSTRAINT pkAluno PRIMARY KEY (ID),
	CONSTRAINT uqAluno UNIQUE (RA_ALUNO),
	CONSTRAINT fkIdCurso FOREIGN KEY (ID_CURSO)
	REFERENCES Curso (ID),
);

CREATE TABLE Professor(
	ID INT IDENTITY(1,1),
	RA_PROF INT NOT NULL,
	APELIDO VARCHAR(30) NOT NULL,
	NOME VARCHAR(120) NOT NULL,
	EMAIL VARCHAR(80) NOT NULL,
	CELULAR CHAR(11) NOT NULL,
	CONSTRAINT pkProfessor PRIMARY KEY (ID),
	CONSTRAINT uqProfessorRa UNIQUE (RA_PROF),
	CONSTRAINT uqProfessorApelido UNIQUE (APELIDO)
);

CREATE TABLE Disciplina_Ofertada(
	ID INT IDENTITY(1,1),
	ID_DISCIP INT NOT NULL,
	ANO SMALLINT NOT NULL,
	SEMESTRE CHAR(1) NOT NULL,
	CONSTRAINT pkDisciplina_Ofertada PRIMARY KEY (ID),
	CONSTRAINT fkDisc_Id FOREIGN KEY (ID_DISCIP)
	REFERENCES Disciplina (ID),
	CONSTRAINT uqDisciplina_Ofertada UNIQUE (ANO, SEMESTRE, ID_DISCIP),	 
);

CREATE TABLE Turma(
	ID INT IDENTITY(1,1),
	ID_TURMA CHAR(1) NOT NULL,
	ID_DISCIP INT NOT NULL,
	ID_PROF INT NOT NULL,
	TURNO VARCHAR(15) NOT NULL,
	CONSTRAINT pkTurma PRIMARY KEY (ID),
	CONSTRAINT uqTurmaTurno UNIQUE (ID_DISCIP, ID_TURMA, TURNO),
	CONSTRAINT fkTurmaIdProf FOREIGN KEY (ID_PROF)
	REFERENCES Professor (ID),
	CONSTRAINT fkTurmaIdDisc FOREIGN KEY (ID_DISCIP)
	REFERENCES Disciplina_Ofertada (ID)			 
);

CREATE TABLE Grade_Curricular(
	ID INT IDENTITY(1,1),
	ID_CURSO INT NOT NULL,
	ANO SMALLINT NOT NULL,
	SEMESTRE CHAR(1) NOT NULL,
	CONSTRAINT pkGradeId PRIMARY KEY (ID),
	CONSTRAINT uqGradeAnoSem UNIQUE (ID_CURSO, ANO, SEMESTRE),
	CONSTRAINT fkGradeSigla FOREIGN KEY (ID_CURSO)
	REFERENCES Curso (ID)
);

CREATE TABLE Periodo(
	ID INT IDENTITY(1,1),
	ID_GRADE INT NOT NULL,
	NUMERO TINYINT NOT NULL,
	CONSTRAINT pkPeriodoNum PRIMARY KEY (ID),
	CONSTRAINT uqPeriodoNum UNIQUE (NUMERO),
	CONSTRAINT fkPeriodoSigla FOREIGN KEY (ID_GRADE)
	REFERENCES Grade_Curricular (ID)
);

CREATE TABLE PeriodoDisciplina(
	ID INT IDENTITY(1,1),
	ID_DISCIP INT NOT NULL,
	ID_PERIODO INT NOT NULL,
	CONSTRAINT pkPeriodoDiscip PRIMARY KEY (ID),	
	CONSTRAINT fkPeriodoNome FOREIGN KEY (ID_DISCIP)
	REFERENCES Disciplina (ID),
	CONSTRAINT fkPeriodoNum FOREIGN KEY (ID_PERIODO)
	REFERENCES Periodo (ID)
);

CREATE TABLE CursoTurma(
	ID INT IDENTITY(1,1),
	ID_CURSO INT NOT NULL,
	ID_TURMA INT NOT NULL,
	CONSTRAINT pkC_TurmaId PRIMARY KEY (ID),
	CONSTRAINT fkCursoTurma_Curso FOREIGN KEY (ID_CURSO)
	REFERENCES Curso (ID),
	CONSTRAINT fkC_TurmaIdTurma FOREIGN KEY (ID_TURMA)
	REFERENCES Turma (ID)
);

CREATE TABLE Matricula(
	ID INT IDENTITY(1,1),
	ID_ALUNO INT NOT NULL,
	ID_TURMA INT NOT NULL,
	CONSTRAINT pkMatriculaId PRIMARY KEY (ID),
	CONSTRAINT fkMatriIdAluno FOREIGN KEY (ID_ALUNO)
	REFERENCES Aluno (ID),
	CONSTRAINT fkMatriIdTurma FOREIGN KEY (ID_TURMA)
	REFERENCES Turma (ID)
);

CREATE TABLE Questao(
	ID INT IDENTITY(1,1),
	ID_TURMA INT NOT NULL,
	NUMERO TINYINT NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	DATA_APLICACAO DATE NOT NULL,
	DATA_LIM_ENTREGA DATE NOT NULL,
	CONSTRAINT pkQuestaId PRIMARY KEY (ID),
	CONSTRAINT uqQuestaoDesc UNIQUE (DESCRICAO, NUMERO),
	CONSTRAINT fkQuestaoId FOREIGN KEY (ID_TURMA)
	REFERENCES Turma (ID)
);

CREATE TABLE Resposta(
	ID INT IDENTITY(1,1),
	ID_ALUNO INT NOT NULL,
	ID_QUESTAO INT NOT NULL,
	DATA_AVALIACAO DATE NOT NULL,
	NOTA DECIMAL(4,2) NOT NULL,
	AVALIACAO VARCHAR(500) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	DATA_ENVIO DATE NOT NULL,
	CONSTRAINT pkResposta PRIMARY KEY (ID),
	CONSTRAINT fkRespostaNumQuestao FOREIGN KEY (ID_QUESTAO)
	REFERENCES Questao (ID),
	CONSTRAINT fkRespostaRaAluno FOREIGN KEY (ID_ALUNO)
	REFERENCES Aluno (ID)
);


CREATE TABLE ArquivosResposta(
	ID INT IDENTITY(1,1),
	ID_RESPOSTA INT NOT NULL,
	ARQUIVO VARCHAR(500) NOT NULL,
	CONSTRAINT fkArquivosNum FOREIGN KEY (ID_RESPOSTA)
	REFERENCES Resposta (ID),
	CONSTRAINT pkArquivosId PRIMARY KEY (ID),
	CONSTRAINT uqRespostaArquivo UNIQUE (ARQUIVO)	
);


CREATE TABLE ArquivosQuestao(
	ID INT IDENTITY(1,1),
	ID_QUESTAO INT NOT NULL,
	ARQUIVO VARCHAR(500) NOT NULL,
	CONSTRAINT pkArquivos PRIMARY KEY (ID),
	CONSTRAINT uqArquivos UNIQUE (ARQUIVO),
	CONSTRAINT fkArquivosQNum FOREIGN KEY (ID_QUESTAO)
	REFERENCES Questao (ID)
);
